name: Generate Datas

on:
  schedule: 
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Gerar a animação Snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Aqueiroz2
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Set environment variable
        run: echo "SNAKE_OUTPUT=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      # Publicar no branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
