name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Aqueiroz2
          outputs: assets/github-contribution-grid-snake.svg

      - name: Check if snake was generated
        run: |
          if [ -s assets/github-contribution-grid-snake.svg ]; then
            echo "✅ Snake generated successfully"
            cat assets/github-contribution-grid-snake.svg | head -5
          else
            echo "❌ Snake file is empty or not generated"
            exit 1
          fi

      - name: Commit & Push
        if: success()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-contribution-grid-snake.svg
          git diff --cached --quiet || git commit -m "Update GitHub Contribution Snake"
          git push
